# app/api/admin_views.py
"""
Admin views (HTML pages):
- /admin            → redirect to scans
- /admin/scans      → list recent scan events (with configurable limit)
- /admin/pharmacies → manage pharmacies + QR download
- /admin/regions    → manage regions
"""

from io import BytesIO
from typing import Optional
from urllib.parse import urlencode

from fastapi import APIRouter, Depends, Form, HTTPException, Request
from fastapi.responses import RedirectResponse, StreamingResponse
from fastapi.templating import Jinja2Templates
from sqlmodel import Session, select

from app.core.deps import get_current_admin, get_session
from app.db.models import Pharmacy, Region, ScanEvent

# Hide admin endpoints from /docs
router = APIRouter(include_in_schema=False)
templates = Jinja2Templates(directory="app/templates")


@router.get("/admin")
def admin_root(
    request: Request,
    admin=Depends(get_current_admin),
):
    """
    Entry point for admins.
    Just redirect to the scan list page.
    """
    return RedirectResponse(url="/admin/scans", status_code=303)


@router.get("/admin/scans")
def admin_scans(
    request: Request,
    session: Session = Depends(get_session),
    admin=Depends(get_current_admin),
    limit: str = "200",
):
    """
    Show a table of recent scan events.

    The 'limit' query parameter controls how many rows are shown:
      - "10", "50", "100", "200" → numeric limit
      - "all" → no limit (all rows from the DB)

    Example URLs:
      /admin/scans?limit=10
      /admin/scans?limit=all
    """
    # Base query: join scan events with pharmacy and region
    base_query = (
        select(ScanEvent, Pharmacy, Region)
        .join(Pharmacy, ScanEvent.pharmacy_id == Pharmacy.id)
        .join(Region, ScanEvent.region_id == Region.id, isouter=True)
        .order_by(ScanEvent.scanned_at.desc())
    )

    applied_limit: Optional[int] = None

    if limit != "all":
        # Try converting limit to int; fallback to 200 on error
        try:
            applied_limit = int(limit)
        except ValueError:
            applied_limit = 200
            limit = "200"

        if applied_limit > 0:
            base_query = base_query.limit(applied_limit)
    else:
        applied_limit = None  # indicates "no limit"

    rows = session.exec(base_query).all()

    # Convert rows into a list of dicts for easy use in the template.
    scans = []
    for scan, ph, reg in rows:
        scans.append(
            {
                "id": scan.id,
                "scanned_at": scan.scanned_at,
                "pharmacy_name": ph.name,
                "region_name": reg.name if reg else None,
                "latitude": scan.latitude,
                "longitude": scan.longitude,
            }
        )

    return templates.TemplateResponse(
        "admin_scans.html",
        {
            "request": request,
            "admin": admin,  # passed to base.html to show admin nav
            "scans": scans,
            "current_limit": limit,  # string ("10", "50", "100", "200", "all")
        },
    )


@router.get("/admin/pharmacies")
def admin_pharmacies(
    request: Request,
    session: Session = Depends(get_session),
    admin=Depends(get_current_admin),
):
    """
    List all pharmacies and provide a form to create new ones.
    """
    pharmacies = session.exec(select(Pharmacy).order_by(Pharmacy.name)).all()
    regions = session.exec(select(Region).order_by(Region.name)).all()
    return templates.TemplateResponse(
        "admin_pharmacies.html",
        {
            "request": request,
            "admin": admin,
            "pharmacies": pharmacies,
            "regions": regions,
        },
    )


@router.post("/admin/pharmacies/create")
def admin_pharmacy_create(
    request: Request,
    name: str = Form(...),
    address: str = Form(""),
    region_id: int = Form(...),
    session: Session = Depends(get_session),
    admin=Depends(get_current_admin),
):
    """
    Handle POST from the "Create new pharmacy" form.

    public_id is auto-generated by the model (default_factory=generate_public_id).
    """
    ph = Pharmacy(
        name=name,
        address=address or None,
        region_id=region_id or None,
    )
    session.add(ph)
    session.commit()
    return RedirectResponse(url="/admin/pharmacies", status_code=303)


@router.get("/admin/pharmacies/{pharmacy_id}/qr")
def admin_pharmacy_qr(
    pharmacy_id: int,
    request: Request,
    session: Session = Depends(get_session),
    admin=Depends(get_current_admin),
):
    """
    Generate a QR code PNG for the given pharmacy.

    The QR content is a full URL:
        <base_url>/?p=<pharmacy_public_id>

    Example:
        http://localhost:8000/?p=abc123

    The response is a downloadable PNG file.
    """
    # 1) Load pharmacy
    pharmacy = session.get(Pharmacy, pharmacy_id)
    if not pharmacy:
        raise HTTPException(status_code=404, detail="Pharmacy not found")

    # 2) Build full URL for the QR payload
    # request.base_url includes trailing slash, e.g. "http://localhost:8000/"
    base_url = str(request.base_url).rstrip("/")
    query = urlencode({"p": pharmacy.public_id})
    qr_text = f"{base_url}/?{query}"

    # 3) Generate QR code PNG in memory
    import qrcode

    qr = qrcode.QRCode(
        version=1,  # automatic size for small payload
        error_correction=qrcode.constants.ERROR_CORRECT_M,
        box_size=10,  # size of each "box" in pixels
        border=4,  # border boxes
    )
    qr.add_data(qr_text)
    qr.make(fit=True)
    img = qr.make_image(fill_color="black", back_color="white")

    buffer = BytesIO()
    img.save(buffer, format="PNG")
    buffer.seek(0)

    # 4) Prepare filename
    safe_name = "".join(c for c in pharmacy.name if c.isalnum() or c in ("-", "_"))
    if not safe_name:
        safe_name = f"pharmacy_{pharmacy.id}"
    filename = f"qr_{safe_name}.png"

    headers = {"Content-Disposition": f'attachment; filename="{filename}"'}
    return StreamingResponse(buffer, media_type="image/png", headers=headers)


@router.get("/admin/regions")
def admin_regions(
    request: Request,
    session: Session = Depends(get_session),
    admin=Depends(get_current_admin),
):
    """
    List regions and show form to create new ones.
    """
    regions = session.exec(select(Region).order_by(Region.name)).all()
    return templates.TemplateResponse(
        "admin_regions.html",
        {
            "request": request,
            "admin": admin,
            "regions": regions,
        },
    )


@router.post("/admin/regions/create")
def admin_region_create(
    request: Request,
    name: str = Form(...),
    code: str = Form(...),
    session: Session = Depends(get_session),
    admin=Depends(get_current_admin),
):
    """
    Create a new region.
    public_id is auto-generated.
    """
    region = Region(
        name=name,
        code=code,
    )
    session.add(region)
    session.commit()
    return RedirectResponse(url="/admin/regions", status_code=303)
